# Generated by Django 4.2.2 on 2026-09-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tag_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='tag',
            new_name='tags',
        ),
    ]
