# Generated by Django 4.2.2 on 2026-09-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
